---
plugin: aws_ec2
regions:
  - ap-southeast-1
user:
  - ubuntu
keyed_groups:
  - key: tags
    prefix: tag
  - prefix: instance_type
    key: instance_type
  - key: placement.region
    prefix: aws_region
